### ISSUE TITLE
#ChangeResolverNaming Change annotations and fields related to resolvers to be more intuitive and readable

### ISSUE THREAD

**Issue by RamAnvesh** [flipkart-incubator/Krystal#104]
Change
`@Resolve(value="dep_name", inputs = {"i1","i2"} )` to 
`@To(dep="dep_name", depInputs = {"i1","i2"} )` 
OR
`@ResolveInputsOf(dep="dep_name", depInputs = {"i1","i2"} )` 

Change
`@BindFrom` to `@From`

**Comment by Jeel11** [comment]
https://github.com/flipkart-incubator/Krystal/pull/113
